/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventTermsRouteImport } from './routes/event-terms'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppOrganiserRouteImport } from './routes/_app/organiser'
import { Route as AppMapRouteImport } from './routes/_app/map'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppHomeRouteImport } from './routes/_app/home'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppCompetitionsRouteImport } from './routes/_app/competitions'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppBookingsRouteImport } from './routes/_app/bookings'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppOrganiserPostEventRouteImport } from './routes/_app/organiser_.post-event'
import { Route as AppOrganiserApplyRouteImport } from './routes/_app/organiser_.apply'
import { Route as AppEventEventIdRouteImport } from './routes/_app/event.$eventId'
import { Route as AppCompetitionsSlugRouteImport } from './routes/_app/competitions_.$slug'
import { Route as AppCheckinBookingIdRouteImport } from './routes/_app/checkin.$bookingId'
import { Route as AppBookingBookingIdRouteImport } from './routes/_app/booking.$bookingId'
import { Route as AppBookEventIdRouteImport } from './routes/_app/book.$eventId'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicQrBookingIdRouteImport } from './routes/api/public/qr.$bookingId'
import { Route as ApiPublicCronRemindersRouteImport } from './routes/api/public/cron/reminders'
import { Route as AppOrganiserEventsEventIdCheckinRouteImport } from './routes/_app/organiser_.events.$eventId.checkin'
import { Route as AppOrganiserEventsEventIdBookingsRouteImport } from './routes/_app/organiser_.events.$eventId.bookings'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventTermsRoute = EventTermsRouteImport.update({
  id: '/event-terms',
  path: '/event-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganiserRoute = AppOrganiserRouteImport.update({
  id: '/organiser',
  path: '/organiser',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitionsRoute = AppCompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganiserPostEventRoute = AppOrganiserPostEventRouteImport.update({
  id: '/organiser_/post-event',
  path: '/organiser/post-event',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganiserApplyRoute = AppOrganiserApplyRouteImport.update({
  id: '/organiser_/apply',
  path: '/organiser/apply',
  getParentRoute: () => AppRoute,
} as any)
const AppEventEventIdRoute = AppEventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitionsSlugRoute = AppCompetitionsSlugRouteImport.update({
  id: '/competitions_/$slug',
  path: '/competitions/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinBookingIdRoute = AppCheckinBookingIdRouteImport.update({
  id: '/checkin/$bookingId',
  path: '/checkin/$bookingId',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingBookingIdRoute = AppBookingBookingIdRouteImport.update({
  id: '/booking/$bookingId',
  path: '/booking/$bookingId',
  getParentRoute: () => AppRoute,
} as any)
const AppBookEventIdRoute = AppBookEventIdRouteImport.update({
  id: '/book/$eventId',
  path: '/book/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQrBookingIdRoute = ApiPublicQrBookingIdRouteImport.update({
  id: '/api/public/qr/$bookingId',
  path: '/api/public/qr/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRemindersRoute = ApiPublicCronRemindersRouteImport.update({
  id: '/api/public/cron/reminders',
  path: '/api/public/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganiserEventsEventIdCheckinRoute =
  AppOrganiserEventsEventIdCheckinRouteImport.update({
    id: '/organiser_/events/$eventId/checkin',
    path: '/organiser/events/$eventId/checkin',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrganiserEventsEventIdBookingsRoute =
  AppOrganiserEventsEventIdBookingsRouteImport.update({
    id: '/organiser_/events/$eventId/bookings',
    path: '/organiser/events/$eventId/bookings',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/event-terms': typeof EventTermsRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AppAdminRoute
  '/bookings': typeof AppBookingsRoute
  '/calendar': typeof AppCalendarRoute
  '/competitions': typeof AppCompetitionsRoute
  '/explore': typeof AppExploreRoute
  '/home': typeof AppHomeRoute
  '/inbox': typeof AppInboxRoute
  '/map': typeof AppMapRoute
  '/organiser': typeof AppOrganiserRoute
  '/profile': typeof AppProfileRoute
  '/book/$eventId': typeof AppBookEventIdRoute
  '/booking/$bookingId': typeof AppBookingBookingIdRoute
  '/checkin/$bookingId': typeof AppCheckinBookingIdRoute
  '/competitions/$slug': typeof AppCompetitionsSlugRoute
  '/event/$eventId': typeof AppEventEventIdRoute
  '/organiser/apply': typeof AppOrganiserApplyRoute
  '/organiser/post-event': typeof AppOrganiserPostEventRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/qr/$bookingId': typeof ApiPublicQrBookingIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/organiser/events/$eventId/bookings': typeof AppOrganiserEventsEventIdBookingsRoute
  '/organiser/events/$eventId/checkin': typeof AppOrganiserEventsEventIdCheckinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/event-terms': typeof EventTermsRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AppAdminRoute
  '/bookings': typeof AppBookingsRoute
  '/calendar': typeof AppCalendarRoute
  '/competitions': typeof AppCompetitionsRoute
  '/explore': typeof AppExploreRoute
  '/home': typeof AppHomeRoute
  '/inbox': typeof AppInboxRoute
  '/map': typeof AppMapRoute
  '/organiser': typeof AppOrganiserRoute
  '/profile': typeof AppProfileRoute
  '/book/$eventId': typeof AppBookEventIdRoute
  '/booking/$bookingId': typeof AppBookingBookingIdRoute
  '/checkin/$bookingId': typeof AppCheckinBookingIdRoute
  '/competitions/$slug': typeof AppCompetitionsSlugRoute
  '/event/$eventId': typeof AppEventEventIdRoute
  '/organiser/apply': typeof AppOrganiserApplyRoute
  '/organiser/post-event': typeof AppOrganiserPostEventRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/qr/$bookingId': typeof ApiPublicQrBookingIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/organiser/events/$eventId/bookings': typeof AppOrganiserEventsEventIdBookingsRoute
  '/organiser/events/$eventId/checkin': typeof AppOrganiserEventsEventIdCheckinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/event-terms': typeof EventTermsRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/bookings': typeof AppBookingsRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/competitions': typeof AppCompetitionsRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/map': typeof AppMapRoute
  '/_app/organiser': typeof AppOrganiserRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/book/$eventId': typeof AppBookEventIdRoute
  '/_app/booking/$bookingId': typeof AppBookingBookingIdRoute
  '/_app/checkin/$bookingId': typeof AppCheckinBookingIdRoute
  '/_app/competitions_/$slug': typeof AppCompetitionsSlugRoute
  '/_app/event/$eventId': typeof AppEventEventIdRoute
  '/_app/organiser_/apply': typeof AppOrganiserApplyRoute
  '/_app/organiser_/post-event': typeof AppOrganiserPostEventRoute
  '/api/public/cron/reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/qr/$bookingId': typeof ApiPublicQrBookingIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/_app/organiser_/events/$eventId/bookings': typeof AppOrganiserEventsEventIdBookingsRoute
  '/_app/organiser_/events/$eventId/checkin': typeof AppOrganiserEventsEventIdCheckinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/event-terms'
    | '/login'
    | '/privacy-policy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin'
    | '/bookings'
    | '/calendar'
    | '/competitions'
    | '/explore'
    | '/home'
    | '/inbox'
    | '/map'
    | '/organiser'
    | '/profile'
    | '/book/$eventId'
    | '/booking/$bookingId'
    | '/checkin/$bookingId'
    | '/competitions/$slug'
    | '/event/$eventId'
    | '/organiser/apply'
    | '/organiser/post-event'
    | '/api/public/cron/reminders'
    | '/api/public/qr/$bookingId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/organiser/events/$eventId/bookings'
    | '/organiser/events/$eventId/checkin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/event-terms'
    | '/login'
    | '/privacy-policy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/admin'
    | '/bookings'
    | '/calendar'
    | '/competitions'
    | '/explore'
    | '/home'
    | '/inbox'
    | '/map'
    | '/organiser'
    | '/profile'
    | '/book/$eventId'
    | '/booking/$bookingId'
    | '/checkin/$bookingId'
    | '/competitions/$slug'
    | '/event/$eventId'
    | '/organiser/apply'
    | '/organiser/post-event'
    | '/api/public/cron/reminders'
    | '/api/public/qr/$bookingId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/organiser/events/$eventId/bookings'
    | '/organiser/events/$eventId/checkin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/event-terms'
    | '/login'
    | '/privacy-policy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/_app/admin'
    | '/_app/bookings'
    | '/_app/calendar'
    | '/_app/competitions'
    | '/_app/explore'
    | '/_app/home'
    | '/_app/inbox'
    | '/_app/map'
    | '/_app/organiser'
    | '/_app/profile'
    | '/_app/book/$eventId'
    | '/_app/booking/$bookingId'
    | '/_app/checkin/$bookingId'
    | '/_app/competitions_/$slug'
    | '/_app/event/$eventId'
    | '/_app/organiser_/apply'
    | '/_app/organiser_/post-event'
    | '/api/public/cron/reminders'
    | '/api/public/qr/$bookingId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
    | '/_app/organiser_/events/$eventId/bookings'
    | '/_app/organiser_/events/$eventId/checkin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  EventTermsRoute: typeof EventTermsRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiPublicCronRemindersRoute: typeof ApiPublicCronRemindersRoute
  ApiPublicQrBookingIdRoute: typeof ApiPublicQrBookingIdRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-terms': {
      id: '/event-terms'
      path: '/event-terms'
      fullPath: '/event-terms'
      preLoaderRoute: typeof EventTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organiser': {
      id: '/_app/organiser'
      path: '/organiser'
      fullPath: '/organiser'
      preLoaderRoute: typeof AppOrganiserRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/competitions': {
      id: '/_app/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof AppCompetitionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookings': {
      id: '/_app/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organiser_/post-event': {
      id: '/_app/organiser_/post-event'
      path: '/organiser/post-event'
      fullPath: '/organiser/post-event'
      preLoaderRoute: typeof AppOrganiserPostEventRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organiser_/apply': {
      id: '/_app/organiser_/apply'
      path: '/organiser/apply'
      fullPath: '/organiser/apply'
      preLoaderRoute: typeof AppOrganiserApplyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/event/$eventId': {
      id: '/_app/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof AppEventEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/competitions_/$slug': {
      id: '/_app/competitions_/$slug'
      path: '/competitions/$slug'
      fullPath: '/competitions/$slug'
      preLoaderRoute: typeof AppCompetitionsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkin/$bookingId': {
      id: '/_app/checkin/$bookingId'
      path: '/checkin/$bookingId'
      fullPath: '/checkin/$bookingId'
      preLoaderRoute: typeof AppCheckinBookingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/booking/$bookingId': {
      id: '/_app/booking/$bookingId'
      path: '/booking/$bookingId'
      fullPath: '/booking/$bookingId'
      preLoaderRoute: typeof AppBookingBookingIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/book/$eventId': {
      id: '/_app/book/$eventId'
      path: '/book/$eventId'
      fullPath: '/book/$eventId'
      preLoaderRoute: typeof AppBookEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/qr/$bookingId': {
      id: '/api/public/qr/$bookingId'
      path: '/api/public/qr/$bookingId'
      fullPath: '/api/public/qr/$bookingId'
      preLoaderRoute: typeof ApiPublicQrBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/reminders': {
      id: '/api/public/cron/reminders'
      path: '/api/public/cron/reminders'
      fullPath: '/api/public/cron/reminders'
      preLoaderRoute: typeof ApiPublicCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/organiser_/events/$eventId/checkin': {
      id: '/_app/organiser_/events/$eventId/checkin'
      path: '/organiser/events/$eventId/checkin'
      fullPath: '/organiser/events/$eventId/checkin'
      preLoaderRoute: typeof AppOrganiserEventsEventIdCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organiser_/events/$eventId/bookings': {
      id: '/_app/organiser_/events/$eventId/bookings'
      path: '/organiser/events/$eventId/bookings'
      fullPath: '/organiser/events/$eventId/bookings'
      preLoaderRoute: typeof AppOrganiserEventsEventIdBookingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBookingsRoute: typeof AppBookingsRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCompetitionsRoute: typeof AppCompetitionsRoute
  AppExploreRoute: typeof AppExploreRoute
  AppHomeRoute: typeof AppHomeRoute
  AppInboxRoute: typeof AppInboxRoute
  AppMapRoute: typeof AppMapRoute
  AppOrganiserRoute: typeof AppOrganiserRoute
  AppProfileRoute: typeof AppProfileRoute
  AppBookEventIdRoute: typeof AppBookEventIdRoute
  AppBookingBookingIdRoute: typeof AppBookingBookingIdRoute
  AppCheckinBookingIdRoute: typeof AppCheckinBookingIdRoute
  AppCompetitionsSlugRoute: typeof AppCompetitionsSlugRoute
  AppEventEventIdRoute: typeof AppEventEventIdRoute
  AppOrganiserApplyRoute: typeof AppOrganiserApplyRoute
  AppOrganiserPostEventRoute: typeof AppOrganiserPostEventRoute
  AppOrganiserEventsEventIdBookingsRoute: typeof AppOrganiserEventsEventIdBookingsRoute
  AppOrganiserEventsEventIdCheckinRoute: typeof AppOrganiserEventsEventIdCheckinRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBookingsRoute: AppBookingsRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCompetitionsRoute: AppCompetitionsRoute,
  AppExploreRoute: AppExploreRoute,
  AppHomeRoute: AppHomeRoute,
  AppInboxRoute: AppInboxRoute,
  AppMapRoute: AppMapRoute,
  AppOrganiserRoute: AppOrganiserRoute,
  AppProfileRoute: AppProfileRoute,
  AppBookEventIdRoute: AppBookEventIdRoute,
  AppBookingBookingIdRoute: AppBookingBookingIdRoute,
  AppCheckinBookingIdRoute: AppCheckinBookingIdRoute,
  AppCompetitionsSlugRoute: AppCompetitionsSlugRoute,
  AppEventEventIdRoute: AppEventEventIdRoute,
  AppOrganiserApplyRoute: AppOrganiserApplyRoute,
  AppOrganiserPostEventRoute: AppOrganiserPostEventRoute,
  AppOrganiserEventsEventIdBookingsRoute:
    AppOrganiserEventsEventIdBookingsRoute,
  AppOrganiserEventsEventIdCheckinRoute: AppOrganiserEventsEventIdCheckinRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  EventTermsRoute: EventTermsRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiPublicCronRemindersRoute: ApiPublicCronRemindersRoute,
  ApiPublicQrBookingIdRoute: ApiPublicQrBookingIdRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
